# Update-WaxFrame.ps1
#
# Companion updater for the WaxFrame Professional portable (file://) install.
# Run manually (right-click -> "Run with PowerShell") from inside this
# WaxFrame folder. Cannot be launched automatically from the browser tab --
# a file:// page has no way to execute a local script, by design (see
# js/update-check.js, which only ever shows instructions pointing here).
#
# What this does: checks GitHub for a newer release, downloads it, checks
# the download is structurally sound, and swaps it in -- keeping your
# current install as a dated backup folder next to this one (never
# deleted). If anything goes wrong partway through, it rolls back
# automatically so you're never left without a working copy.
#
# Deliberate scope decisions (not gaps -- stated up front):
#   - This script targets Windows/PowerShell. Mac/Linux portable installs
#     use the sibling Update-WaxFrame.command script.
#   - Release ZIPs are manually named assets generated by the release-assets
#     workflow. A separately downloaded SHA-256 manifest is required and
#     verified before extraction. GitHub also publishes a signed build-
#     provenance attestation for the ZIP for independent `gh attestation
#     verify` checks.
#   - No user-data migration step. WaxFrame keeps everything you create
#     in the browser (IndexedDB/localStorage) or in a folder you pick
#     yourself via a save dialog -- never inside this app folder. So the
#     whole folder is safe to rename/replace wholesale.
#   - No running-process coordination. A file:// page isn't a process to
#     wait on or restart -- "relaunch" just means reopening index.html.
#
# Build: 20260906-004

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$Repo = 'WeirDave/WaxFrame-Professional'

function Write-Step($msg) { Write-Host $msg -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host $msg -ForegroundColor Green }
function Write-Err($msg)  { Write-Host $msg -ForegroundColor Red }
function Write-Warn($msg) { Write-Host $msg -ForegroundColor Yellow }

function Compare-WfVersion($a, $b) {
  $pa = ($a -replace '^v', '') -split '\.' | ForEach-Object { [int]($_ -as [int]) }
  $pb = ($b -replace '^v', '') -split '\.' | ForEach-Object { [int]($_ -as [int]) }
  $len = [Math]::Max($pa.Count, $pb.Count)
  for ($i = 0; $i -lt $len; $i++) {
    $av = if ($i -lt $pa.Count) { $pa[$i] } else { 0 }
    $bv = if ($i -lt $pb.Count) { $pb[$i] } else { 0 }
    if ($av -gt $bv) { return 1 }
    if ($av -lt $bv) { return -1 }
  }
  return 0
}

function Get-WfVersion($root) {
  $versionFile = Join-Path $root 'js\version.js'
  if (-not (Test-Path $versionFile)) { return $null }
  $content = Get-Content -Raw -LiteralPath $versionFile
  if ($content -match "const\s+APP_VERSION\s*=\s*['""]v?([\d.]+)\s+Pro['""]") {
    return $Matches[1]
  }
  return $null
}

$RequiredFiles = @(
  'index.html', 'ai-api-pricing.html', 'ai-business-proposal.html', 'ai-cover-letter-editor.html',
  'ai-resume-review.html', 'api-details.html', 'document-playbooks.html', 'help.html',
  'hive-profiles.html', 'privacy.html', 'prompt-editor.html', 'start-here.html',
  'templates.html', 'terms.html', 'waxframe-user-manual.html', 'what-are-tokens.html',
  'js\version.js', 'js\app.js', 'style.css'
)

function Test-WfReleaseTree($root, $expectedVersion) {
  foreach ($f in $RequiredFiles) {
    if (-not (Test-Path (Join-Path $root $f))) {
      throw "Downloaded release is missing expected file: $f"
    }
  }
  $ver = Get-WfVersion $root
  if (-not $ver) { throw "Downloaded release: could not read APP_VERSION from js\version.js" }
  if ($expectedVersion -and ($ver -ne $expectedVersion)) {
    throw "Downloaded release version mismatch: expected $expectedVersion, found $ver"
  }
  return $ver
}

# ---- 1. Resolve install root + current version ------------------------------
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
if (-not (Test-Path (Join-Path $scriptDir 'index.html'))) {
  Write-Err "This script must run from inside a WaxFrame install folder (index.html not found next to it)."
  Read-Host "Press Enter to close"
  exit 1
}
$currentVersion = Get-WfVersion $scriptDir
if (-not $currentVersion) {
  Write-Err "Could not read the current version from js\version.js."
  Read-Host "Press Enter to close"
  exit 1
}
Write-Step "WaxFrame Professional updater -- currently v$currentVersion"

# ---- 2. Check latest release --------------------------------------------------
Write-Step "Checking for updates..."
try {
  $release = Invoke-RestMethod -Uri "https://api.github.com/repos/$Repo/releases/latest" `
    -Headers @{ Accept = 'application/vnd.github+json' } -UseBasicParsing
} catch {
  Write-Err "Could not reach GitHub to check for updates: $($_.Exception.Message)"
  Read-Host "Press Enter to close"
  exit 1
}
$latestTag = [string]$release.tag_name
$latestVersion = $latestTag -replace '^v', ''
if ($latestTag -notmatch '^v[0-9]+(?:\.[0-9]+)+$') {
  Write-Err "GitHub returned an unexpected release tag: $latestTag"
  Read-Host "Press Enter to close"
  exit 1
}
if ((Compare-WfVersion $latestVersion $currentVersion) -le 0) {
  Write-Ok "Already up to date (v$currentVersion)."
  Read-Host "Press Enter to close"
  exit 0
}
Write-Ok "v$latestVersion is available (you have v$currentVersion)."

# ---- 2b. Git fast path ---------------------------------------------------------
# A folder cloned from GitHub updates by fetching and checking out the release
# tag: a few KB of objects instead of the whole ZIP, and the previous version
# stays in the object store as its own rollback. The ZIP path below is
# unchanged and still handles every other install.
#
# Refuses on a working copy with unpushed commits or edited tracked files --
# checking a release tag out over in-progress work is not an update.
function Test-WfGit {
  try { & git --version *>$null; return $LASTEXITCODE -eq 0 } catch { return $false }
}

function Invoke-WfGit {
  param([string[]]$Arguments, [switch]$AllowFailure)
  $output = & git -C $scriptDir @Arguments 2>&1
  if ($LASTEXITCODE -ne 0 -and -not $AllowFailure) {
    throw "git $($Arguments -join ' ') failed: $output"
  }
  return $output
}

function Get-WfDirtyTrackedPaths {
  $lines = Invoke-WfGit -Arguments @('status', '--porcelain') -AllowFailure
  $dirty = @()
  foreach ($line in @($lines)) {
    $text = "$line"
    if ($text.Trim().Length -eq 0) { continue }
    if ($text.Substring(0, 2).Trim() -eq '??') { continue }  # untracked never blocks
    $dirty += $text.Substring(3).Trim().Trim('"')
  }
  return $dirty
}

if ((Test-Path (Join-Path $scriptDir '.git')) -and (Test-WfGit)) {
  Write-Step 'This copy is a git checkout -- updating with git.'
  try {
    $head = (Invoke-WfGit -Arguments @('rev-parse', '--abbrev-ref', 'HEAD') -AllowFailure | Out-String).Trim()
    $onBranch = $head -and $head -ne 'HEAD'
    $ahead = 0
    if ($onBranch) {
      $aheadText = (Invoke-WfGit -Arguments @('rev-list', '--count', '@{u}..HEAD') -AllowFailure | Out-String).Trim()
      if ($aheadText -match '^\d+$') { $ahead = [int]$aheadText }
    }
    $dirty = Get-WfDirtyTrackedPaths

    if ($onBranch -and ($ahead -gt 0 -or $dirty.Count -gt 0)) {
      Write-Err 'This checkout has local work -- unpushed commits or edited files.'
      Write-Err 'Updating would check a release tag out over it. Use git directly.'
      Read-Host 'Press Enter to close'
      exit 1
    }
    if ($dirty.Count -gt 0) {
      Write-Err "These tracked files have local edits: $($dirty -join ', ')"
      Write-Err 'Revert or move them, then run this again.'
      Read-Host 'Press Enter to close'
      exit 1
    }

    Write-Step 'Fetching from GitHub...'
    Invoke-WfGit -Arguments @('fetch', '--tags', '--prune', 'origin') | Out-Null
    Write-Step "Checking out $latestTag..."
    Invoke-WfGit -Arguments @('-c', 'advice.detachedHead=false', 'checkout', '--force', $latestTag) | Out-Null

    $installedVersion = Get-WfVersion $scriptDir
    Write-Ok "Updated to v$installedVersion. Nothing was downloaded or replaced --"
    Write-Ok "your previous version is still in git if you ever need it back."
    Write-Step 'Reopening WaxFrame...'
    Start-Process (Join-Path $scriptDir 'index.html')
    Read-Host 'Press Enter to close'
    exit 0
  } catch {
    Write-Warn "Git update didn't complete: $($_.Exception.Message)"
    Write-Warn 'Falling back to the download method.'
  }
}

# ---- 3. Download into staging --------------------------------------------------
# Staged OUTSIDE $scriptDir, in %TEMP%. Staging inside the install folder
# would break step 8's atomic swap: once $scriptDir gets renamed to the
# backup name, every path computed under it (this staging folder included)
# would silently move along with it, invalidating $extractedRoot mid-run.
$staging = Join-Path $env:TEMP "WaxFrameUpdate-$([guid]::NewGuid().ToString('N'))"
New-Item -ItemType Directory -Path $staging -Force | Out-Null
$zipPath = Join-Path $staging 'download.zip'
$checksumPath = Join-Path $staging 'download.sha256'
$extractPath = Join-Path $staging 'extracted'

function Remove-Staging {
  if (Test-Path $staging) { Remove-Item -LiteralPath $staging -Recurse -Force -ErrorAction SilentlyContinue }
}

try {
  Write-Step "Downloading v$latestVersion..."
  $assetName = "WaxFrame-Professional-$latestVersion.zip"
  $checksumName = "$assetName.sha256"
  $releaseBaseUrl = "https://github.com/$Repo/releases/download/$latestTag"
  $downloadUrl = "$releaseBaseUrl/$assetName"
  $checksumUrl = "$releaseBaseUrl/$checksumName"
  Invoke-WebRequest -Uri $downloadUrl -OutFile $zipPath -UseBasicParsing
  Invoke-WebRequest -Uri $checksumUrl -OutFile $checksumPath -UseBasicParsing

  Write-Step "Verifying SHA-256..."
  $checksumText = (Get-Content -LiteralPath $checksumPath -Raw).Trim()
  if ($checksumText -notmatch '^(?<hash>[A-Fa-f0-9]{64})(?:\s+\*?[^\r\n]+)?$') {
    throw "Release checksum manifest is malformed"
  }
  $expectedHash = $Matches['hash'].ToLowerInvariant()
  $actualHash = (Get-FileHash -LiteralPath $zipPath -Algorithm SHA256).Hash.ToLowerInvariant()
  if ($actualHash -ne $expectedHash) {
    throw "Release SHA-256 mismatch -- expected $expectedHash, got $actualHash"
  }
  Write-Ok "SHA-256 verified: $actualHash"

  # ---- 4/5. Extract + handle GitHub's wrapper folder --------------------------
  Write-Step "Extracting..."
  Expand-Archive -LiteralPath $zipPath -DestinationPath $extractPath -Force
  $children = Get-ChildItem -LiteralPath $extractPath -Directory
  if ($children.Count -ne 1) {
    throw "Unexpected archive layout: expected exactly one top-level folder, found $($children.Count)."
  }
  $extractedRoot = $children[0].FullName

  # ---- 6/7. Validate the already checksum-verified tree structurally -----------
  Write-Step "Verifying..."
  Test-WfReleaseTree $extractedRoot $latestVersion | Out-Null
  Write-Ok "Verified: v$latestVersion, all required files present."

  # ---- 8. Atomic swap with backup ----------------------------------------------
  Write-Step "Installing..."
  $parent = Split-Path -Parent $scriptDir
  $folderName = Split-Path -Leaf $scriptDir
  $timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
  $backupLeaf = "$folderName.previous-$currentVersion-$timestamp"
  $backupPath = Join-Path $parent $backupLeaf

  Rename-Item -LiteralPath $scriptDir -NewName $backupLeaf -ErrorAction Stop
  try {
    Move-Item -LiteralPath $extractedRoot -Destination $scriptDir -ErrorAction Stop
  } catch {
    # Roll back: put the original folder's name back so the user is never
    # left without a working copy.
    if ((Test-Path $backupPath) -and (-not (Test-Path $scriptDir))) {
      Rename-Item -LiteralPath $backupPath -NewName $folderName -ErrorAction SilentlyContinue
    }
    throw
  }

  Write-Ok "Updated to v$latestVersion. Your previous copy is kept at:"
  Write-Ok "  $backupPath"

  # ---- 9. Relaunch ---------------------------------------------------------------
  Write-Step "Reopening WaxFrame..."
  Start-Process (Join-Path $scriptDir 'index.html')

} catch {
  Write-Err "Update failed: $($_.Exception.Message)"
  Write-Err "Nothing was left half-installed -- your previous copy is intact."
  Read-Host "Press Enter to close"
  exit 1
} finally {
  Remove-Staging
}

Read-Host "Press Enter to close"
